// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADMWTVm_ay94CsZf54Qm-ZDGeBXe1ENA',
    appId: '1:493243482176:web:b58df4affd7941ea51dfa5',
    messagingSenderId: '493243482176',
    projectId: 'paipao-app',
    authDomain: 'paipao-app.firebaseapp.com',
    storageBucket: 'paipao-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHO-md3bSGZhsGJpA-CQt_n93iAxgrZ0Q',
    appId: '1:493243482176:android:798106cd7cb16c4151dfa5',
    messagingSenderId: '493243482176',
    projectId: 'paipao-app',
    storageBucket: 'paipao-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNBDGdIWgN9qs-7P8qtUq4R5YJ2Cjw93s',
    appId: '1:493243482176:ios:faf959c9b30293ea51dfa5',
    messagingSenderId: '493243482176',
    projectId: 'paipao-app',
    storageBucket: 'paipao-app.appspot.com',
    iosClientId:
        '493243482176-d12i02ll1lfbvtqnoscoc0u8ffll4rd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.paipao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNBDGdIWgN9qs-7P8qtUq4R5YJ2Cjw93s',
    appId: '1:493243482176:ios:faf959c9b30293ea51dfa5',
    messagingSenderId: '493243482176',
    projectId: 'paipao-app',
    storageBucket: 'paipao-app.appspot.com',
    iosClientId:
        '493243482176-d12i02ll1lfbvtqnoscoc0u8ffll4rd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.paipao',
  );
}
